# Generated by Django 5.0.4 on 2024-04-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaloriePage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caloriesconsumption',
            options={'ordering': ['status']},
        ),
        migrations.AddField(
            model_name='caloriesconsumption',
            name='foodCalorie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
